spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/guames/microservices-config-repository

server:
  port: 8888
